#!/bin/bash -e

required_bins=( "docker" "npm" )
for b in "${required_bins[@]}"; do
	if ! command -v ${b} &>/dev/null; then
		echo "Required bin missing: ${b}"
		exit 1
	fi
done

npm install
npm run build

container_name=hollow-local

echo "Building local container"
docker build -q -t hollow-local docker 

[ -z "$(docker ps -aq --filter name=${container_name})" ] || docker rm -f ${container_name}
docker run -d --name ${container_name} -v ${PWD}:/var/lib/ghost/content/themes/hollow -p 3000:2368 hollow-local

echo -n "Waiting for container to initialise..."
until docker logs ${container_name} 2>&1 | grep -q "initial entrypoint"; do
  echo -n "."
  sleep 1
done
echo -e "\033[32mOK\033[00m"

echo -e "Ghost running at \033[34mhttp://localhost:3000\033[00m\n"
echo -e "Admin Email: \033[34mghost@example.com\033[00m"
echo -e "Admin Password: \033[34mghostadmin\033[00m"